"use server";

import { signIn, signOut } from "@/auth";
import { AuthError } from "next-auth";

/**
 * Server Action to handle user login.
 * Compatible with React 19's useActionState.
 */
export async function loginAction(_prevState: unknown, formData: FormData) {
  const email = formData.get("email");
  const password = formData.get("password");

  if (!email || !password) {
    return { error: "El correo y la contraseña son obligatorios." };
  }

  try {
    await signIn("credentials", {
      email: email.toString().trim(),
      password: password.toString(),
      redirect: true,
      redirectTo: "/", // Let middleware route to the correct dashboard based on role
    });
  } catch (error) {
    if (error instanceof AuthError) {
      // In next-auth, credentials validation failure results in CredentialsSignin or CallbackRouteError
      switch (error.type) {
        case "CredentialsSignin":
        case "CallbackRouteError":
          return { error: "Credenciales incorrectas. Verifique su correo y contraseña." };
        default:
          return { error: "Ocurrió un error al iniciar sesión. Inténtelo de nuevo." };
      }
    }
    // MUST rethrow redirect errors generated by NextAuth / Next.js redirect
    throw error;
  }
}

/**
 * Server Action to handle user logout.
 */
export async function logoutAction() {
  await signOut({ redirectTo: "/login" });
}
